2023-11-08 21:36:23 +0800 4400 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 21:51:46 +0800 4818 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 21:56:54 +0800 5045 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 21:59:14 +0800 5152 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:02:58 +0800 5266 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:04:34 +0800 5342 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:08:17 +0800 5522 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:09:15 +0800 5653 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:09:42 +0800 5714 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:10:00 +0800 5790 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:10:40 +0800 5890 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:13:38 +0800 6252 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:15:12 +0800 6360 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:16:53 +0800 6564 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:19:08 +0800 6732 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
2023-11-08 22:19:41 +0800 6741 ERROR [/usr/local/lib/python3.11/dist-packages/sanic/handlers/error.py:188] Exception occurred while handling uri: 'http://192.168.252.156/know:site/visit?target=PYTHON%2F%E6%80%A7%E8%83%BD%E5%A2%9E%E5%BC%BA.STACKLESS.site&tk=undefined'
Traceback (most recent call last):
  File "handle_request", line 97, in handle_request
  File "/home/zin/Desktop/_Y/TPA/know/sc_bp.py", line 17, in _
    return jsonify(KnowHelper.visit(':'.join((APP, edp)), request.args.get('target')))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zin/Desktop/_Y/TPA/know/assistant.py", line 13, in visit
    data = cls.ly(cls.a_dfp(app, target))
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zin/Desktop/_Y/TPA/base.py", line 376, in a_dfp
    ap = cls.a_ddp(app)
         ^^^^^^^^^^^^^^
  File "/home/zin/Desktop/_Y/TPA/base.py", line 392, in a_ddp
    a, e = a.split(':') if ':' in a else (a, None)
    ^^^^
ValueError: too many values to unpack (expected 2)
2023-11-08 22:38:55 +0800 7789 WARNING [/usr/local/lib/python3.11/dist-packages/sanic/mixins/startup.py:542] [01;33mSanic is running in PRODUCTION mode. Consider using '--debug' or '--dev' while actively developing your application.[0m
